In [6]:
import numpy as np
import mnist
from tensorflow import keras
from keras.utils import to_categorical

In [7]:
train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()
print(train_images.shape)
print(train_labels[0])

(60000, 28, 28)
5


In [8]:
train_images_nor=(train_images/255)-0.5
test_images_nor=(test_images/255)-0.5

In [9]:
train_images = train_images_nor.reshape((-1,784))
test_images = test_images_nor.reshape((-1,784))

In [10]:
from keras.models import Sequential
from keras.layers import Dense

In [18]:
model = Sequential()
model.add(Dense(8,input_dim=784,activation='sigmoid'))
model.add(Dense(8, activation='sigmoid'))
model.add(Dense(10, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [19]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 8)                 6280      
                                                                 
 dense_4 (Dense)             (None, 8)                 72        
                                                                 
 dense_5 (Dense)             (None, 10)                90        
                                                                 
Total params: 6,442
Trainable params: 6,442
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.fit(train_images, to_categorical(train_labels), epochs=20, batch_size=32)

Epoch 1/20
1875/1875 [==============================] - 4s 2ms/step - loss: 1.6465 - accuracy: 0.5495
Epoch 2/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.9325 - accuracy: 0.7674
Epoch 3/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.6631 - accuracy: 0.8368
Epoch 4/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.5420 - accuracy: 0.8581
Epoch 5/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4850 - accuracy: 0.8679
Epoch 6/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4526 - accuracy: 0.8753
Epoch 7/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4321 - accuracy: 0.8789
Epoch 8/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4152 - accuracy: 0.8832
Epoch 9/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4043 - accuracy: 0.8864
Epoch 10/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.391

In [21]:
predictions=np.argmax(model.predict(test_images),axis=1)

313/313 [==============================] - 0s 1ms/step


In [16]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [22]:
print(classification_report(test_labels,predictions))
print(confusion_matrix(test_labels,predictions))
print(accuracy_score(test_labels,predictions))

              precision    recall  f1-score   support

           0       0.93      0.96      0.95       980
           1       0.95      0.97      0.96      1135
           2       0.90      0.86      0.88      1032
           3       0.87      0.90      0.88      1010
           4       0.88      0.95      0.92       982
           5       0.87      0.84      0.86       892
           6       0.92      0.92      0.92       958
           7       0.90      0.92      0.91      1028
           8       0.92      0.82      0.87       974
           9       0.90      0.88      0.89      1009

    accuracy                           0.90     10000
   macro avg       0.90      0.90      0.90     10000
weighted avg       0.90      0.90      0.90     10000

[[ 944    3    7    7    1    7    4    6    1    0]
 [   0 1105    2    3    1    5    5    9    4    1]
 [   7    3  887   26   17    6   31   29   25    1]
 [  18    1   26  906    1   15    1   15   18    9]
 [   0    1    7    1  936   