In [4]:
from tensorflow import keras
import numpy as np
import mnist

In [2]:
train_images=mnist.train_images()
test_images=mnist.test_images()
test_labels=mnist.test_labels()
train_labels=mnist.train_labels()

In [3]:
test_images=(test_images/255)-0.5
train_images=(train_images/255)-0.5

In [5]:
train_images=np.expand_dims(train_images,axis=3)
test_images=np.expand_dims(test_images,axis=3)

In [8]:
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Flatten
num_filters=8
filter_size=3
pool_size=2
model=Sequential()
model.add(Conv2D(num_filters,filter_size,input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=pool_size))
model.add(Flatten())
model.add(Dense(10,activation='softmax'))

In [9]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_1 (Conv2D)           (None, 26, 26, 8)         80        
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 13, 13, 8)        0         
 2D)                                                             
                                                                 
 flatten_1 (Flatten)         (None, 1352)              0         
                                                                 
 dense_1 (Dense)             (None, 10)                13530     
                                                                 
Total params: 13,610
Trainable params: 13,610
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [11]:
from keras.utils import to_categorical

In [13]:
model.fit(train_images,to_categorical(train_labels),epochs=5,batch_size=32)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1690 - accuracy: 0.9517
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1276 - accuracy: 0.9627
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1065 - accuracy: 0.9690
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0922 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0823 - accuracy: 0.9752


In [16]:
predictions=np.argmax(model.predict(test_images),axis=1)

313/313 [==============================] - 1s 2ms/step


In [15]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [17]:
print(classification_report(test_labels,predictions))
print(confusion_matrix(test_labels,predictions))
print(accuracy_score(test_labels,predictions))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.98      0.99      0.99      1135
           2       0.95      0.97      0.96      1032
           3       0.97      0.97      0.97      1010
           4       0.97      0.98      0.98       982
           5       0.97      0.98      0.98       892
           6       0.99      0.97      0.98       958
           7       0.96      0.97      0.96      1028
           8       0.98      0.96      0.97       974
           9       0.99      0.93      0.96      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

[[ 968    0    3    0    1    1    1    4    2    0]
 [   1 1128    5    1    0    0    0    0    0    0]
 [   0    4 1005    4    5    1    2    7    4    0]
 [   0    0    3  984    0    9    0    8    6    0]
 [   1    1    6    0  964   