## Checking the time taken by numpy library and loops
### Initializing matrices and importing modules

In [27]:
import time as T
import numpy as np
raw_1=np.random.randint(25, size=(10,10))
raw_2=np.random.randint(25, size=(10,10))
array_1=np.array(raw_1)
array_2=np.array(raw_2)
add=np.zeros((10,10))
multiply=np.zeros((10,10))

### Function defining 

In [28]:
def addMatrix(A,B):
    for i in range(len(A)):
        for j in range(len(A)):
            add[i][j] = A[i][j] + B[i][j]
    return print("addition using loops\n", add)

def multiMatrix(A, B):
    for i in range(len(A)):
        for j in range(len(A)):
            for k in range(len(B)):
                multiply[i][j] += A[i][k] * B[k][j]
    return print("multiplication using loops\n", multiply)
    
def invert_matrix(BC):
    n = len(BC)
    I=np.identity(n)
    indices = list(range(n))
    for fd in range(n):
        diagScaler = 1.0 / BC[fd][fd] 
        for j in range(n):
            BC[fd][j] *= diagScaler
            I[fd][j] *= diagScaler
        for i in indices[0:fd] + indices[fd+1:]: 
            ro_op = BC[i][fd]
            for j in range(n): 
                BC[i][j] = BC[i][j] - ro_op * BC[fd][j]
                I[i][j] = I[i][j] - ro_op * I[fd][j]
    return I

### Addition

In [29]:
#using loops
start1=T.time()
addMatrix(raw_1, raw_2)
end1=T.time()

#using numpy
start2=T.time()
nadd=np.add(raw_1,raw_2)
end2=T.time()
print("addition using numpy\n", nadd)


addition using loops
 [[14. 29. 23. 41. 29.  5. 14. 25. 19. 28.]
 [ 6. 46. 12. 22. 22. 31. 24. 15. 24.  6.]
 [25. 43. 29. 16. 26. 33. 23. 24. 22. 20.]
 [35. 27. 21. 32. 29. 30. 32. 45. 14. 31.]
 [ 3. 26. 36. 14. 15.  8. 18. 24. 30. 38.]
 [26. 29. 18.  5. 30. 23. 14.  2. 27. 39.]
 [33. 25. 40. 28. 23.  8. 27. 45. 19. 16.]
 [ 9. 35. 38. 23. 17. 38. 21.  3. 26. 39.]
 [35. 38. 35.  7. 20. 25. 14. 29. 27.  2.]
 [23. 17. 35. 14. 22. 39. 26. 30. 19. 22.]]
addition using numpy
 [[14 29 23 41 29  5 14 25 19 28]
 [ 6 46 12 22 22 31 24 15 24  6]
 [25 43 29 16 26 33 23 24 22 20]
 [35 27 21 32 29 30 32 45 14 31]
 [ 3 26 36 14 15  8 18 24 30 38]
 [26 29 18  5 30 23 14  2 27 39]
 [33 25 40 28 23  8 27 45 19 16]
 [ 9 35 38 23 17 38 21  3 26 39]
 [35 38 35  7 20 25 14 29 27  2]
 [23 17 35 14 22 39 26 30 19 22]]


### Multiplication

In [30]:
start3=T.time()
multiMatrix(raw_1,raw_2)
end3=T.time()

#using numpy
start4=T.time()
nmultiply=np.matmul(array_1,array_2)
end4=T.time()
print("multiplication using numpy\n",nmultiply)

multiplication using loops
 [[ 958. 1333. 1512. 1213. 1012. 1690. 1250. 1213. 1096. 1246.]
 [ 961. 1687. 1761. 1360. 1292. 1794. 1317. 1313. 1606. 1408.]
 [1123. 1718. 1870. 1412. 1469. 2005. 1116.  914. 1417. 1690.]
 [ 969. 1573. 2112. 1555. 1417. 1717. 1532. 1133. 1208. 1693.]
 [ 893. 1985. 1907. 1503. 1267. 2282. 1632. 1204. 1370. 1188.]
 [ 797. 1047. 1335.  878.  931. 1458.  874.  908. 1110. 1086.]
 [1090. 2167. 2145. 1990. 1617. 1970. 1605. 1535. 1597. 1596.]
 [1157. 1535. 1992.  964. 1307. 1995. 1230. 1157. 1424. 1091.]
 [ 638. 1556. 1555. 1189. 1044. 1419.  884. 1010. 1174.  939.]
 [1136. 1958. 2297. 1421. 1608. 2085. 1474. 1192. 1630. 1539.]]
multiplication using numpy
 [[ 958 1333 1512 1213 1012 1690 1250 1213 1096 1246]
 [ 961 1687 1761 1360 1292 1794 1317 1313 1606 1408]
 [1123 1718 1870 1412 1469 2005 1116  914 1417 1690]
 [ 969 1573 2112 1555 1417 1717 1532 1133 1208 1693]
 [ 893 1985 1907 1503 1267 2282 1632 1204 1370 1188]
 [ 797 1047 1335  878  931 1458  874  908 1110 1

### Inversion
- for inverse we applied jordan elimination and row operations simultaneously for matrix and a identity matrix

In [31]:
#using numpy
start5=T.time()
ninv=np.linalg.inv(array_1)
end5=T.time()

#using loops
start6=T.time()
invert_matrix(raw_1)
end6=T.time()


## Comparision of time factors:
- numpy = factor x loops

In [32]:
print(f"""addition => factor={(end1-start1)/(end2-start2)}
multiply => factor={(end3-start3)/(end4-start4)}
inverse  => factor={(end6-start6)/(end5-start5)}""")

addition => factor=21.723076923076924
multiply => factor=27.28482972136223
inverse  => factor=15.476749239461103
